<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\Home\_ViewImports.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\css\site.css">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\chat.js">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Shared\" />
    <Folder Include="Properties\PublishProfiles\" />
    <Folder Include="wwwroot\html\" />
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.4.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.4.1" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.5.0" />
    <PackageReference Include="itext.bouncy-castle-fips-adapter" Version="9.5.0" />
    <PackageReference Include="itext.pdfhtml" Version="6.3.1" />
    <PackageReference Include="Lofcz.Forks.HtmlToOpenXml" Version="3.2.5" />
    <PackageReference Include="Markdig" Version="1.1.1" />
    <PackageReference Include="ModelContextProtocol" Version="1.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="System.ClientModel" Version="1.9.0" />
    
  </ItemGroup>

  <ItemGroup>
    <Reference Include="OpenAI">
      <HintPath>OpenAI.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
